{{- if and .Values.auth.enabled .Values.auth.postgres.enabled (not .Values.auth.postgres.existingSecret.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-auth-pg-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ required "auth.postgres.user must be specified" .Values.auth.postgres.user | b64enc }}
  password: {{ required "auth.postgres.password must be specified" .Values.auth.postgres.password | b64enc }}
{{- end }}
{{- if and .Values.auth.enabled .Values.auth.mysql.enabled (not .Values.auth.mysql.existingSecret.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-auth-mysql-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ required "auth.mysql.user must be specified" .Values.auth.mysql.user | b64enc }}
  password: {{ required "auth.mysql.password must be specified" .Values.auth.mysql.password | b64enc }}
{{- end }}
