apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPortName }}
      protocol: TCP
      name: {{ .Values.service.name }}
    {{- if .Values.oauth2Proxy.enabled }}
    - port: {{ include "mlflow.servicePort" $ }}
      targetPort: oauth2-proxy
      protocol: TCP
      name: oauth2-proxy
    {{- end }}
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
